CREATE TABLE `successcase` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `tenantId` INTEGER NOT NULL,
  `slug` VARCHAR(160) NOT NULL,
  `businessName` VARCHAR(180) NOT NULL,
  `logoUrl` VARCHAR(255) NULL,
  `coverUrl` VARCHAR(255) NULL,
  `businessType` VARCHAR(100) NOT NULL,
  `location` VARCHAR(180) NOT NULL,
  `initialProblem` TEXT NOT NULL,
  `solution` TEXT NOT NULL,
  `features` TEXT NOT NULL,
  `results` TEXT NOT NULL,
  `gallery` JSON NULL,
  `testimonial` TEXT NULL,
  `websiteUrl` VARCHAR(500) NULL,
  `planName` VARCHAR(120) NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'published',
  `sortOrder` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `successcase_tenantId_slug_key` (`tenantId`, `slug`),
  INDEX `successcase_tenantId_status_sortOrder_idx` (`tenantId`, `status`, `sortOrder`),
  PRIMARY KEY (`id`),
  CONSTRAINT `successcase_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `tenant` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
