import Link from "next/link";

const navigation = [
  ["/funcionalidades", "Producto"],
  ["/multi-sucursal", "Multi-sucursal"],
  ["/clientes", "Clientes"],
  ["/planes", "Planes"],
] as const;

/** @summary Chrome comercial exclusivo de MenuClick Platform, separado de tenants y superadmin. */
export function MarketingShell({ children }: { children: React.ReactNode }) {
  return <div className="marketing-theme min-h-screen bg-[#0b0d12] text-white"><header className="sticky top-0 z-50 border-b border-white/10 bg-[#0b0d12]/90 backdrop-blur-xl"><nav className="mx-auto flex min-h-[4.5rem] max-w-[1280px] items-center justify-between gap-5 px-5" aria-label="Navegación comercial MenuClick"><Link href="/" className="flex items-center gap-2 text-xl font-black tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e8ff6a] text-sm text-[#0b0d12]">M</span><span>MenuClick<span className="text-[#e8ff6a]">.</span></span></Link><div className="hidden items-center gap-1 lg:flex">{navigation.map(([href, label]) => <Link className="rounded-lg px-3 py-2 text-sm font-bold text-slate-300 transition hover:bg-white/10 hover:text-white" href={href} key={href}>{label}</Link>)}</div><div className="flex items-center gap-2"><Link className="hidden rounded-lg px-3 py-2 text-sm font-bold text-slate-300 hover:bg-white/10 hover:text-white sm:inline-flex" href="/login">Ingresar</Link><Link className="rounded-lg bg-[#e8ff6a] px-3 py-2 text-sm font-black text-[#0b0d12] hover:bg-[#f1ff9c] sm:px-4" href="/solicitar-demo">Solicitar demo</Link></div></nav></header>{children}<footer className="border-t border-white/10 bg-[#080a0e]"><div className="mx-auto grid max-w-[1280px] gap-10 px-5 py-14 sm:grid-cols-2 lg:grid-cols-4"><div><Link className="text-xl font-black" href="/">MenuClick<span className="text-[#e8ff6a]">.</span></Link><p className="mt-3 max-w-xs text-sm leading-relaxed text-slate-500">La operación digital para negocios gastronómicos que quieren crecer sin perder el control.</p></div><div><h2 className="text-sm font-black text-white">Producto</h2><div className="mt-4 grid gap-2 text-sm text-slate-400"><Link href="/funcionalidades">Funcionalidades</Link><Link href="/multi-sucursal">Multi-sucursal</Link><Link href="/planes">Planes</Link></div></div><div><h2 className="text-sm font-black text-white">Empresa</h2><div className="mt-4 grid gap-2 text-sm text-slate-400"><Link href="/para-negocios">Para negocios</Link><Link href="/clientes">Clientes</Link><Link href="/solicitar-demo">Contacto</Link></div></div><div><h2 className="text-sm font-black text-white">Acceso</h2><div className="mt-4 grid gap-2 text-sm text-slate-400"><Link href="/login">Ingresar</Link><Link href="/legal">Privacidad y términos</Link></div></div></div><p className="mx-auto max-w-[1280px] px-5 pb-8 text-xs text-slate-600">© {new Date().getFullYear()} MenuClick. Plataforma para gastronomía.</p></footer></div>;
}
