import Image from "next/image";
import Link from "next/link";
import { MarketingShell } from "@/components/commercial/marketing-shell";
import { ProductMockup } from "@/components/commercial/product-mockup";
import { StickyStorySection } from "@/components/commercial/sticky-story-section";

type PlanSummary = { id: number; slug: string; name: string; summary: string; highlighted: boolean; price: { amount: number | null; currency: string; billingPeriod: string } | null };
type PublicCase = { id: number; slug: string; businessName: string; businessType: string; location: string; coverUrl: string | null; results: string; tenantName: string };

const audiences = ["Hamburgueserías", "Cervecerías", "Bares", "Cafeterías", "Restaurantes", "Fast food", "Food trucks", "Cadenas y franquicias"];

function BranchVisual() {
  return <div className="mx-auto max-w-md rounded-3xl border border-white/15 bg-[#151a22] p-5 shadow-2xl shadow-black/30"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-xs font-black uppercase tracking-[.2em] text-[#e8ff6a]">Empresa</span><span className="rounded-full bg-[#e8ff6a]/15 px-2 py-1 text-[10px] font-bold text-[#e8ff6a]">4 locales</span></div><div className="relative mt-5 grid gap-3 pl-8"><span className="absolute bottom-5 left-3 top-5 w-px bg-white/15" />{["Palermo", "Belgrano", "Centro", "Costanera"].map((branch, index) => <div className="relative flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.04] px-3 py-3 text-sm font-bold" key={branch}><span className="absolute -left-[1.15rem] h-px w-4 bg-white/20" /><span className={`h-2.5 w-2.5 rounded-full ${index === 0 ? "bg-[#e8ff6a]" : "bg-cyan-300"}`} />{branch}<span className="ml-auto text-[10px] text-slate-500">Activa</span></div>)}</div></div>;
}

function AudienceStrip() {
  return <section className="border-y border-white/10 bg-[#10151d]"><div className="mx-auto max-w-[1280px] px-5 py-16"><p className="marketing-eyebrow">Para quién es</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Una base adaptable para cada forma de hacer gastronomía.</h2><div className="mt-7 flex flex-wrap gap-2">{audiences.map((audience) => <span className="rounded-full border border-white/10 bg-white/[.04] px-4 py-2 text-sm font-bold text-slate-300" key={audience}>{audience}</span>)}</div></div></section>;
}

/** @summary Landing comercial de MenuClick con narrativa de producto y operación gastronómica real. */
export function MenuClickHome({ plans, cases }: { plans: PlanSummary[]; cases: PublicCase[] }) {
  const operationSteps = [
    { eyebrow: "01 · Carta digital", title: "Tu carta se actualiza cuando vos decidís.", description: "Productos, categorías, precios, disponibilidad, promociones y opciones en una experiencia que el cliente entiende desde el celular.", visual: <ProductMockup mode="menu" /> },
    { eyebrow: "02 · Pedidos", title: "Del primer click al pedido entregado.", description: "Recibí pedidos, revisá cada detalle y avanzá estados desde un tablero operativo, sin perder el contexto del cliente.", visual: <ProductMockup mode="orders" /> },
    { eyebrow: "03 · Reservas", title: "Más previsibilidad para cada turno.", description: "Organizá reservas, capacidad, horarios y bloqueos con reglas claras para que el equipo trabaje con información actual.", visual: <ProductMockup mode="dashboard" /> },
    { eyebrow: "04 · Inventario", title: "Sabé qué hay disponible en cada local.", description: "Controlá existencias, mínimos y movimientos por sucursal. El stock deja de ser una planilla aislada.", visual: <ProductMockup mode="stock" /> },
    { eyebrow: "05 · Clientes", title: "La relación no termina en la compra.", description: "Conservá una base de clientes frecuentes, puntos e historial para construir visitas que vuelven.", visual: <ProductMockup mode="customers" /> },
    { eyebrow: "06 · Estadísticas", title: "Tomá decisiones con señales reales.", description: "Entendé pedidos, productos, reservas y recorridos para saber qué está funcionando y qué conviene ajustar.", visual: <ProductMockup mode="analytics" /> },
  ];
  const customerSteps = [
    { eyebrow: "01 · Presencia propia", title: "Cada negocio tiene una identidad reconocible.", description: "Una landing pública, carta, datos de contacto y estilo visual propios. MenuClick no reemplaza tu marca: la ordena.", visual: <ProductMockup mode="dashboard" compact /> },
    { eyebrow: "02 · Carta", title: "Sin PDF, sin zoom, sin versiones viejas.", description: "El cliente encuentra productos, precios, variantes y disponibilidad en una experiencia responsive y actualizable.", visual: <ProductMockup mode="menu" compact /> },
    { eyebrow: "03 · Pedido", title: "Comprar tiene que sentirse simple.", description: "El recorrido desde el celular mantiene claridad en cantidades, notas, modalidad y total antes de confirmar.", visual: <ProductMockup mode="orders" compact /> },
    { eyebrow: "04 · Fidelización", title: "Una razón concreta para volver.", description: "Puntos y clientes frecuentes convierten una visita aislada en una relación que el negocio puede cuidar.", visual: <ProductMockup mode="customers" compact /> },
  ];
  return <MarketingShell><main>
    <section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(232,255,106,.14),transparent_30%),radial-gradient(circle_at_20%_80%,rgba(103,232,249,.1),transparent_32%)]" /><div className="relative mx-auto grid min-h-[calc(100vh-4.5rem)] max-w-[1280px] items-center gap-14 px-5 py-20 lg:grid-cols-[.9fr_1.1fr] lg:py-28"><div><p className="marketing-eyebrow">Sistema operativo para gastronomía</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[.94] tracking-[-.06em] sm:text-7xl lg:text-8xl">Todo tu negocio gastronómico, conectado.</h1><p className="mt-7 max-w-xl text-lg leading-relaxed text-slate-300">Carta digital, pedidos, reservas, stock, clientes y sucursales en una plataforma que tu equipo puede usar todos los días.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="rounded-xl bg-[#e8ff6a] px-5 py-3 font-black text-[#0b0d12] hover:bg-[#f1ff9c]" href="/solicitar-demo">Solicitar demo</Link><Link className="rounded-xl border border-white/15 px-5 py-3 font-bold text-white hover:bg-white/10" href="#producto">Ver cómo funciona</Link></div></div><div className="relative"><div className="absolute -inset-8 rounded-full bg-[#e8ff6a]/10 blur-3xl" /><ProductMockup mode="dashboard" /></div></div></section>
    <section className="mx-auto max-w-[1280px] px-5 py-20 sm:py-28" id="producto"><p className="marketing-eyebrow">Una plataforma, varias capas</p><h2 className="mt-4 max-w-4xl text-4xl font-black tracking-tight sm:text-6xl">La operación que se ve. La información que sostiene el negocio.</h2><p className="mt-5 max-w-2xl text-lg leading-relaxed text-slate-400">MenuClick conecta lo que tu cliente experimenta con lo que tu equipo necesita resolver detrás de escena.</p><div className="mt-12 grid gap-4 md:grid-cols-3">{[["01", "Experiencia pública", "Landing, carta, pedidos, reservas y fidelización."], ["02", "Operación diaria", "Pedidos, inventario, mesas, sucursales y usuarios."], ["03", "Decisiones", "Actividad y estadísticas para saber dónde ajustar."]].map(([number, heading, copy]) => <article className="rounded-2xl border border-white/10 bg-white/[.035] p-5" key={number}><span className="text-3xl text-[#e8ff6a]">{number}</span><h3 className="mt-8 text-xl font-black">{heading}</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">{copy}</p></article>)}</div></section>
    <AudienceStrip />
    <StickyStorySection eyebrow="La operación" title="Todo pasa por MenuClick." intro="Una herramienta para el equipo, no una pantalla más que nadie abre." steps={operationSteps} />
    <StickyStorySection eyebrow="La experiencia del cliente" title="Administrar mejor también se nota afuera." intro="La plataforma ordena el trabajo interno y mejora cada interacción que ve tu cliente." steps={customerSteps} reverse />
    <section className="border-y border-white/10 bg-[#111720]" id="multi-sucursal"><div className="mx-auto grid max-w-[1280px] items-center gap-12 px-5 py-24 lg:grid-cols-2"><div><p className="marketing-eyebrow">Para crecer con control</p><h2 className="mt-4 text-4xl font-black sm:text-6xl">Una sucursal o veinte. El control sigue siendo uno.</h2><p className="mt-5 max-w-xl text-lg leading-relaxed text-slate-400">Cada local puede tener su operación, stock y usuarios autorizados. El propietario conserva una mirada consolidada.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Control central", "Usuarios por sucursal", "Stock independiente", "Pedidos y reservas", "Estadísticas consolidadas", "Crecimiento sin rehacer todo"].map((item) => <div className="rounded-xl border border-white/10 bg-white/[.035] p-4 text-sm font-bold" key={item}><span className="mr-2 text-[#e8ff6a]">↗</span>{item}</div>)}</div><Link className="mt-8 inline-flex rounded-xl border border-[#e8ff6a]/40 px-4 py-3 font-black text-[#e8ff6a]" href="/multi-sucursal">Conocer multi-sucursal →</Link></div><BranchVisual /></div></section>
    <section className="mx-auto max-w-[1280px] px-5 py-24" id="clientes"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="marketing-eyebrow">Social proof verificable</p><h2 className="mt-4 text-4xl font-black sm:text-5xl">Negocios que ya forman parte de la historia.</h2></div><Link className="font-black text-[#e8ff6a]" href="/clientes">Ver clientes →</Link></div><div className="mt-10 grid gap-5 md:grid-cols-2">{cases.slice(0, 2).map((item) => <Link className="group overflow-hidden rounded-2xl border border-white/10 bg-white/[.035]" href={`/clientes/${item.slug}`} key={item.id}><div className="relative aspect-[16/7] bg-[#1a202c]">{item.coverUrl && <Image src={`/images/images_cases/${item.coverUrl}`} alt={`Caso ${item.businessName}`} fill className="object-cover transition duration-500 group-hover:scale-105" />}</div><div className="p-5"><p className="text-xs font-black uppercase tracking-widest text-[#e8ff6a]">{item.tenantName} · {item.businessType}</p><h3 className="mt-2 text-2xl font-black">{item.businessName}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-400">{item.results}</p></div></Link>)}{!cases.length && <div className="rounded-2xl border border-dashed border-white/15 p-8 text-slate-400">Estamos preparando los primeros casos públicos de MenuClick.</div>}</div></section>
    <section className="border-y border-white/10 bg-[#0f131a]" id="planes"><div className="mx-auto max-w-[1280px] px-5 py-24"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="marketing-eyebrow">Planes comerciales</p><h2 className="mt-4 text-4xl font-black sm:text-5xl">Elegí el plan que acompaña tu etapa.</h2></div><Link className="font-black text-[#e8ff6a]" href="/planes">Comparar planes →</Link></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{plans.slice(0, 4).map((plan) => <article className={`rounded-2xl border p-5 ${plan.highlighted ? "border-[#e8ff6a]/50 bg-[#e8ff6a]/10" : "border-white/10 bg-white/[.035]"}`} key={plan.id}><h3 className="text-xl font-black">{plan.name}</h3><p className="mt-3 min-h-16 text-sm leading-relaxed text-slate-400">{plan.summary}</p>{plan.price && <p className="mt-5 text-lg font-black">{plan.price.amount === null ? "A cotizar" : `${plan.price.currency} ${plan.price.amount.toLocaleString("es-AR")}`}</p>}<Link className="mt-6 inline-block text-sm font-black text-[#e8ff6a]" href={`/solicitar-demo?plan=${encodeURIComponent(plan.name)}`}>Consultar este plan →</Link></article>)}</div></div></section>
    <section className="mx-auto max-w-[1280px] px-5 py-24"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="marketing-eyebrow">Cómo funciona</p><h2 className="mt-4 text-4xl font-black sm:text-5xl">De la idea a una operación conectada.</h2></div><ol className="grid gap-3 sm:grid-cols-2">{["Creamos tu negocio y definimos el alcance.", "Configurás carta, marca y operación.", "Publicás tu sitio y tu carta.", "Administrás todo desde MenuClick."].map((step, index) => <li className="flex gap-4 rounded-xl border border-white/10 bg-white/[.035] p-5" key={step}><span className="text-xl font-black text-[#e8ff6a]">0{index + 1}</span><strong>{step}</strong></li>)}</ol></div></section>
    <section className="mx-auto max-w-[1280px] px-5 pb-28"><div className="overflow-hidden rounded-[2rem] border border-[#e8ff6a]/30 bg-[#e8ff6a] p-8 text-[#0b0d12] sm:p-14"><p className="text-sm font-black uppercase tracking-[.2em]">El próximo paso</p><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Tu negocio ya está funcionando. Ahora hacelo funcionar conectado.</h2><div className="mt-8 flex flex-wrap gap-3"><Link className="rounded-xl bg-[#0b0d12] px-5 py-3 font-black text-white" href="/solicitar-demo">Solicitar demo</Link><Link className="rounded-xl border border-[#0b0d12]/30 px-5 py-3 font-black" href="/planes">Ver planes</Link></div></div></section>
  </main></MarketingShell>;
}
