"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Tenant = Awaited<ReturnType<typeof import("@/lib/platform-data").platformTenants>>[number];

function storage(bytes: number) {
  return bytes < 1_000_000 ? `${(bytes / 1_000).toFixed(1)} KB` : `${(bytes / 1_000_000).toFixed(1)} MB`;
}

export function ClientList({ tenants, adminBaseUrl }: { tenants: Tenant[]; adminBaseUrl: string }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all");
  const [expanded, setExpanded] = useState<Set<number>>(new Set());
  const visible = useMemo(
    () => tenants.filter((tenant) => (!query.trim() || `${tenant.name} ${tenant.slug} ${tenant.brandSettings?.customDomain ?? ""}`.toLocaleLowerCase("es").includes(query.trim().toLocaleLowerCase("es"))) && (status === "all" || tenant.status === status || tenant.subscription?.status === status)),
    [query, status, tenants],
  );

  return <section>
    <header className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.25em] text-amber-300">MenuClick Platform / Operación</p><h1 className="mt-2 text-4xl font-black tracking-tight sm:text-5xl">Clientes</h1><p className="mt-3 max-w-2xl text-base leading-relaxed text-slate-400">Una vista operativa para encontrar negocios, revisar su actividad y entrar a su ficha completa.</p></div><Link className="rounded-xl bg-amber-400 px-4 py-3 text-sm font-black text-slate-950 hover:bg-amber-300" href="/superadmin/clientes/nuevo">Nuevo cliente</Link></header>
    <div className="mb-5 grid gap-3 rounded-2xl border border-white/10 bg-[#151a24] p-4 md:grid-cols-[minmax(260px,1fr)_180px_auto]"><input className="min-h-12 rounded-xl border border-white/10 bg-[#202735] px-4 text-white outline-none focus:border-amber-300" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por negocio, slug o dominio" type="search" /><select className="min-h-12 rounded-xl border border-white/10 bg-[#202735] px-4 text-white" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Todos los estados</option><option value="active">Activos</option><option value="suspended">Suspendidos</option><option value="TRIAL">Trial</option><option value="PAYMENT_PENDING">Pago pendiente</option></select><span className="self-center text-sm text-slate-400">{visible.length} resultados</span></div>
    <div className="overflow-hidden rounded-2xl border border-white/10 bg-[#151a24]"><div className="hidden grid-cols-[minmax(230px,1.5fr)_150px_120px_120px_150px_230px] gap-4 border-b border-white/10 px-5 py-4 text-xs font-black uppercase tracking-wider text-slate-500 lg:grid"><span>Cliente</span><span>Estado / plan</span><span>Sucursales</span><span>Usuarios</span><span>Actividad</span><span>Accesos</span></div>{visible.map((tenant) => { const open = expanded.has(tenant.id); const adminUrl = `${adminBaseUrl}/login?tenantId=${tenant.id}`; return <div className="border-b border-white/10 last:border-0" key={tenant.id}><div className="grid gap-3 px-5 py-5 lg:grid-cols-[minmax(230px,1.5fr)_150px_120px_120px_150px_230px] lg:items-center"><div><div className="flex items-center gap-3"><button className="text-slate-400 hover:text-white" onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(tenant.id)) next.delete(tenant.id); else next.add(tenant.id); return next; })} aria-label={`${open ? "Ocultar" : "Mostrar"} sucursales de ${tenant.name}`} type="button">{open ? "▼" : "▶"}</button><div><Link className="text-lg font-black hover:text-amber-300" href={`/superadmin/clientes/${tenant.id}`}>{tenant.name}</Link><p className="text-sm text-slate-500">{tenant.slug} {tenant.brandSettings?.customDomain ? `· ${tenant.brandSettings.customDomain}` : ""}</p></div></div></div><div><span className={`font-bold ${tenant.status === "active" ? "text-emerald-300" : "text-rose-300"}`}>{tenant.status === "active" ? "Activo" : "Suspendido"}</span><p className="text-sm text-slate-400">{tenant.subscription?.plan?.name ?? "Sin plan"}</p></div><span className="text-slate-300">{tenant.branches.length}</span><span className="text-slate-300">{tenant._count.memberships}</span><span className="text-sm text-slate-400">{tenant._count.customerOrders} pedidos · {storage(tenant.storageBytes)}</span><div className="flex flex-wrap gap-2"><a className="rounded-lg border border-emerald-300/30 px-2.5 py-2 text-xs font-black text-emerald-200 hover:bg-emerald-300/10" href={tenant.publicUrl} target="_blank" rel="noreferrer">Ver landing ↗</a><a className="rounded-lg border border-amber-300/30 px-2.5 py-2 text-xs font-black text-amber-200 hover:bg-amber-300/10" href={adminUrl} target="_blank" rel="noreferrer">Administración ↗</a></div></div>{open && <div className="ml-8 grid gap-2 border-l border-amber-300/30 px-5 pb-5 sm:grid-cols-3">{tenant.branches.map((branch) => <Link className="rounded-xl border border-white/10 bg-[#202735] p-3 hover:border-amber-300/50" href={`/superadmin/clientes/${tenant.id}?branchId=${branch.id}`} key={branch.id}><strong className="block">{branch.name}</strong><span className="mt-1 block text-xs text-slate-400">{branch.active ? "Activa" : "Inactiva"} · {branch._count.orders} pedidos</span></Link>)}</div>}</div>; })}{!visible.length && <p className="p-12 text-center text-slate-400">No encontramos clientes con esos filtros.</p>}</div>
  </section>;
}
