ALTER TABLE `product`
  ADD COLUMN `model3dUrl` VARCHAR(500) NULL,
  ADD COLUMN `usdzUrl` VARCHAR(500) NULL,
  ADD COLUMN `modelPosterUrl` VARCHAR(500) NULL,
  ADD COLUMN `arEnabled` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN `arScale` DECIMAL(8, 3) NOT NULL DEFAULT 1.000,
  ADD COLUMN `modelWidthCm` DECIMAL(8, 2) NULL,
  ADD COLUMN `modelHeightCm` DECIMAL(8, 2) NULL,
  ADD COLUMN `modelDepthCm` DECIMAL(8, 2) NULL,
  ADD COLUMN `modelOrientation` VARCHAR(80) NOT NULL DEFAULT '0deg 0deg 0deg',
  ADD COLUMN `arPlacement` VARCHAR(20) NOT NULL DEFAULT 'floor',
  ADD COLUMN `arAllowScale` BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN `modelUpdatedAt` DATETIME(3) NULL;
